<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('delivery/search', [\App\Domains\Delivery\Controllers\DeliveryController::class, 'search']);
// 新增接口
Route::post('delivery/store', [\App\Domains\Delivery\Controllers\DeliveryController::class, 'store']);
// 获取详情接口
Route::get('delivery/show', [\App\Domains\Delivery\Controllers\DeliveryController::class, 'show'])->name('delivery.show');
// 更新接口
Route::put('delivery/update', [\App\Domains\Delivery\Controllers\DeliveryController::class, 'update']);
// 删除接口
Route::post('delivery/destroy', [\App\Domains\Delivery\Controllers\DeliveryController::class, 'destroy']);
