<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('wechatUser/search', [\App\Domains\Wechat\Controllers\WechatUserController::class, 'search']);
// 新增接口
Route::post('wechatUser/store', [\App\Domains\Wechat\Controllers\WechatUserController::class, 'store']);
// 获取详情接口
Route::get('wechatUser/show', [\App\Domains\Wechat\Controllers\WechatUserController::class, 'show'])->name('wechatUser.show');
// 更新接口
Route::put('wechatUser/update', [\App\Domains\Wechat\Controllers\WechatUserController::class, 'update']);
// 删除接口
Route::post('wechatUser/destroy', [\App\Domains\Wechat\Controllers\WechatUserController::class, 'destroy']);
