<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('systemRegion/search', [\App\Domains\System\Controllers\SystemRegionController::class, 'search']);
// 新增接口
Route::post('systemRegion/store', [\App\Domains\System\Controllers\SystemRegionController::class, 'store']);
// 获取详情接口
Route::get('systemRegion/show', [\App\Domains\System\Controllers\SystemRegionController::class, 'show'])->name('systemRegion.show');
// 更新接口
Route::put('systemRegion/update', [\App\Domains\System\Controllers\SystemRegionController::class, 'update']);
// 删除接口
Route::post('systemRegion/destroy', [\App\Domains\System\Controllers\SystemRegionController::class, 'destroy']);
// 查询列表接口
Route::post('systemSetting/search', [\App\Domains\System\Controllers\SystemSettingController::class, 'search']);
// 新增接口
Route::post('systemSetting/store', [\App\Domains\System\Controllers\SystemSettingController::class, 'store']);
// 获取详情接口
Route::get('systemSetting/show', [\App\Domains\System\Controllers\SystemSettingController::class, 'show'])->name('systemSetting.show');
// 更新接口
Route::put('systemSetting/update', [\App\Domains\System\Controllers\SystemSettingController::class, 'update']);
// 删除接口
Route::post('systemSetting/destroy', [\App\Domains\System\Controllers\SystemSettingController::class, 'destroy']);
