<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('cart/search', [\App\Domains\Cart\Controllers\CartController::class, 'search']);
// 新增接口
Route::post('cart/store', [\App\Domains\Cart\Controllers\CartController::class, 'store']);
// 获取详情接口
Route::get('cart/show', [\App\Domains\Cart\Controllers\CartController::class, 'show'])->name('cart.show');
// 更新接口
Route::put('cart/update', [\App\Domains\Cart\Controllers\CartController::class, 'update']);
// 删除接口
Route::post('cart/destroy', [\App\Domains\Cart\Controllers\CartController::class, 'destroy']);
