<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Modules\Portal\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

// Portal Index
Route::get('/', [IndexController::class, 'index'])->name('index');
