<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Modules\Portal\Controllers\AuthController;
use App\Modules\Portal\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

// 登录页面
Route::get('login', [AuthController::class, 'login'])->name('login');
// 提交登录
Route::post('login', [AuthController::class, 'authenticate']);
// 退出登录
Route::post('logout', [AuthController::class, 'logout']);
// 获取接口
Route::get('/', [IndexController::class, 'index'])->name('index');
