<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Api\Portal\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

// 获取接口
Route::get('/', [IndexController::class, 'index'])->name('index');
