<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('payment/search', [\App\Domains\Payment\Controllers\PaymentController::class, 'search']);
// 新增接口
Route::post('payment/store', [\App\Domains\Payment\Controllers\PaymentController::class, 'store']);
// 获取详情接口
Route::get('payment/show', [\App\Domains\Payment\Controllers\PaymentController::class, 'show'])->name('payment.show');
// 更新接口
Route::put('payment/update', [\App\Domains\Payment\Controllers\PaymentController::class, 'update']);
// 删除接口
Route::post('payment/destroy', [\App\Domains\Payment\Controllers\PaymentController::class, 'destroy']);
