<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('comment/search', [\App\Domains\Comment\Controllers\CommentController::class, 'search']);
// 新增接口
Route::post('comment/store', [\App\Domains\Comment\Controllers\CommentController::class, 'store']);
// 获取详情接口
Route::get('comment/show', [\App\Domains\Comment\Controllers\CommentController::class, 'show'])->name('comment.show');
// 更新接口
Route::put('comment/update', [\App\Domains\Comment\Controllers\CommentController::class, 'update']);
// 删除接口
Route::post('comment/destroy', [\App\Domains\Comment\Controllers\CommentController::class, 'destroy']);
