<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('content/search', [\App\Domains\Content\Controllers\ContentController::class, 'search']);
// 新增接口
Route::post('content/store', [\App\Domains\Content\Controllers\ContentController::class, 'store']);
// 获取详情接口
Route::get('content/show', [\App\Domains\Content\Controllers\ContentController::class, 'show'])->name('content.show');
// 更新接口
Route::put('content/update', [\App\Domains\Content\Controllers\ContentController::class, 'update']);
// 删除接口
Route::post('content/destroy', [\App\Domains\Content\Controllers\ContentController::class, 'destroy']);
