<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('inventory/search', [\App\Domains\Inventory\Controllers\InventoryController::class, 'search']);
// 新增接口
Route::post('inventory/store', [\App\Domains\Inventory\Controllers\InventoryController::class, 'store']);
// 获取详情接口
Route::get('inventory/show', [\App\Domains\Inventory\Controllers\InventoryController::class, 'show'])->name('inventory.show');
// 更新接口
Route::put('inventory/update', [\App\Domains\Inventory\Controllers\InventoryController::class, 'update']);
// 删除接口
Route::post('inventory/destroy', [\App\Domains\Inventory\Controllers\InventoryController::class, 'destroy']);
