// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// adPositionsDao is the data access object for the table ad_positions.
// You can define custom methods on it to extend its functionality as needed.
type adPositionsDao struct {
	*internal.AdPositionsDao
}

var (
	// AdPositions is a globally accessible object for table ad_positions operations.
	AdPositions = adPositionsDao{internal.NewAdPositionsDao()}
)

// Add your custom methods and functionality below.
