// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// adsDao is the data access object for the table ads.
// You can define custom methods on it to extend its functionality as needed.
type adsDao struct {
	*internal.AdsDao
}

var (
	// Ads is a globally accessible object for table ads operations.
	Ads = adsDao{internal.NewAdsDao()}
)

// Add your custom methods and functionality below.
