// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// attachmentRelationsDao is the data access object for the table attachment_relations.
// You can define custom methods on it to extend its functionality as needed.
type attachmentRelationsDao struct {
	*internal.AttachmentRelationsDao
}

var (
	// AttachmentRelations is a globally accessible object for table attachment_relations operations.
	AttachmentRelations = attachmentRelationsDao{internal.NewAttachmentRelationsDao()}
)

// Add your custom methods and functionality below.
