// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// blocksDao is the data access object for the table blocks.
// You can define custom methods on it to extend its functionality as needed.
type blocksDao struct {
	*internal.BlocksDao
}

var (
	// Blocks is a globally accessible object for table blocks operations.
	Blocks = blocksDao{internal.NewBlocksDao()}
)

// Add your custom methods and functionality below.
