// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// contentsDao is the data access object for the table contents.
// You can define custom methods on it to extend its functionality as needed.
type contentsDao struct {
	*internal.ContentsDao
}

var (
	// Contents is a globally accessible object for table contents operations.
	Contents = contentsDao{internal.NewContentsDao()}
)

// Add your custom methods and functionality below.
