// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// contentRevisionsDao is the data access object for the table content_revisions.
// You can define custom methods on it to extend its functionality as needed.
type contentRevisionsDao struct {
	*internal.ContentRevisionsDao
}

var (
	// ContentRevisions is a globally accessible object for table content_revisions operations.
	ContentRevisions = contentRevisionsDao{internal.NewContentRevisionsDao()}
)

// Add your custom methods and functionality below.
