// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// contentPushQueueDao is the data access object for the table content_push_queue.
// You can define custom methods on it to extend its functionality as needed.
type contentPushQueueDao struct {
	*internal.ContentPushQueueDao
}

var (
	// ContentPushQueue is a globally accessible object for table content_push_queue operations.
	ContentPushQueue = contentPushQueueDao{internal.NewContentPushQueueDao()}
)

// Add your custom methods and functionality below.
