// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// contentModelsDao is the data access object for the table content_models.
// You can define custom methods on it to extend its functionality as needed.
type contentModelsDao struct {
	*internal.ContentModelsDao
}

var (
	// ContentModels is a globally accessible object for table content_models operations.
	ContentModels = contentModelsDao{internal.NewContentModelsDao()}
)

// Add your custom methods and functionality below.
