// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// dataArticleDao is the data access object for the table data_article.
// You can define custom methods on it to extend its functionality as needed.
type dataArticleDao struct {
	*internal.DataArticleDao
}

var (
	// DataArticle is a globally accessible object for table data_article operations.
	DataArticle = dataArticleDao{internal.NewDataArticleDao()}
)

// Add your custom methods and functionality below.
