// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// formTemplatesDao is the data access object for the table form_templates.
// You can define custom methods on it to extend its functionality as needed.
type formTemplatesDao struct {
	*internal.FormTemplatesDao
}

var (
	// FormTemplates is a globally accessible object for table form_templates operations.
	FormTemplates = formTemplatesDao{internal.NewFormTemplatesDao()}
)

// Add your custom methods and functionality below.
