// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// formSubmissionsDao is the data access object for the table form_submissions.
// You can define custom methods on it to extend its functionality as needed.
type formSubmissionsDao struct {
	*internal.FormSubmissionsDao
}

var (
	// FormSubmissions is a globally accessible object for table form_submissions operations.
	FormSubmissions = formSubmissionsDao{internal.NewFormSubmissionsDao()}
)

// Add your custom methods and functionality below.
