// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// friendLinksDao is the data access object for the table friend_links.
// You can define custom methods on it to extend its functionality as needed.
type friendLinksDao struct {
	*internal.FriendLinksDao
}

var (
	// FriendLinks is a globally accessible object for table friend_links operations.
	FriendLinks = friendLinksDao{internal.NewFriendLinksDao()}
)

// Add your custom methods and functionality below.
