// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// modelFieldsDao is the data access object for the table model_fields.
// You can define custom methods on it to extend its functionality as needed.
type modelFieldsDao struct {
	*internal.ModelFieldsDao
}

var (
	// ModelFields is a globally accessible object for table model_fields operations.
	ModelFields = modelFieldsDao{internal.NewModelFieldsDao()}
)

// Add your custom methods and functionality below.
