// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// navItemsDao is the data access object for the table nav_items.
// You can define custom methods on it to extend its functionality as needed.
type navItemsDao struct {
	*internal.NavItemsDao
}

var (
	// NavItems is a globally accessible object for table nav_items operations.
	NavItems = navItemsDao{internal.NewNavItemsDao()}
)

// Add your custom methods and functionality below.
