// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// navMenusDao is the data access object for the table nav_menus.
// You can define custom methods on it to extend its functionality as needed.
type navMenusDao struct {
	*internal.NavMenusDao
}

var (
	// NavMenus is a globally accessible object for table nav_menus operations.
	NavMenus = navMenusDao{internal.NewNavMenusDao()}
)

// Add your custom methods and functionality below.
