// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// pageTemplatesDao is the data access object for the table page_templates.
// You can define custom methods on it to extend its functionality as needed.
type pageTemplatesDao struct {
	*internal.PageTemplatesDao
}

var (
	// PageTemplates is a globally accessible object for table page_templates operations.
	PageTemplates = pageTemplatesDao{internal.NewPageTemplatesDao()}
)

// Add your custom methods and functionality below.
