// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// permissionsDao is the data access object for the table permissions.
// You can define custom methods on it to extend its functionality as needed.
type permissionsDao struct {
	*internal.PermissionsDao
}

var (
	// Permissions is a globally accessible object for table permissions operations.
	Permissions = permissionsDao{internal.NewPermissionsDao()}
)

// Add your custom methods and functionality below.
