// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// recycleBinDao is the data access object for the table recycle_bin.
// You can define custom methods on it to extend its functionality as needed.
type recycleBinDao struct {
	*internal.RecycleBinDao
}

var (
	// RecycleBin is a globally accessible object for table recycle_bin operations.
	RecycleBin = recycleBinDao{internal.NewRecycleBinDao()}
)

// Add your custom methods and functionality below.
