// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// redirectsDao is the data access object for the table redirects.
// You can define custom methods on it to extend its functionality as needed.
type redirectsDao struct {
	*internal.RedirectsDao
}

var (
	// Redirects is a globally accessible object for table redirects operations.
	Redirects = redirectsDao{internal.NewRedirectsDao()}
)

// Add your custom methods and functionality below.
