// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// seoMetaDao is the data access object for the table seo_meta.
// You can define custom methods on it to extend its functionality as needed.
type seoMetaDao struct {
	*internal.SeoMetaDao
}

var (
	// SeoMeta is a globally accessible object for table seo_meta operations.
	SeoMeta = seoMetaDao{internal.NewSeoMetaDao()}
)

// Add your custom methods and functionality below.
