// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// shortLinksDao is the data access object for the table short_links.
// You can define custom methods on it to extend its functionality as needed.
type shortLinksDao struct {
	*internal.ShortLinksDao
}

var (
	// ShortLinks is a globally accessible object for table short_links operations.
	ShortLinks = shortLinksDao{internal.NewShortLinksDao()}
)

// Add your custom methods and functionality below.
