// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// shortLinkClicksDao is the data access object for the table short_link_clicks.
// You can define custom methods on it to extend its functionality as needed.
type shortLinkClicksDao struct {
	*internal.ShortLinkClicksDao
}

var (
	// ShortLinkClicks is a globally accessible object for table short_link_clicks operations.
	ShortLinkClicks = shortLinkClicksDao{internal.NewShortLinkClicksDao()}
)

// Add your custom methods and functionality below.
