// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// sitesDao is the data access object for the table sites.
// You can define custom methods on it to extend its functionality as needed.
type sitesDao struct {
	*internal.SitesDao
}

var (
	// Sites is a globally accessible object for table sites operations.
	Sites = sitesDao{internal.NewSitesDao()}
)

// Add your custom methods and functionality below.
