// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// statisticsDailyDao is the data access object for the table statistics_daily.
// You can define custom methods on it to extend its functionality as needed.
type statisticsDailyDao struct {
	*internal.StatisticsDailyDao
}

var (
	// StatisticsDaily is a globally accessible object for table statistics_daily operations.
	StatisticsDaily = statisticsDailyDao{internal.NewStatisticsDailyDao()}
)

// Add your custom methods and functionality below.
