// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// termRelationshipsDao is the data access object for the table term_relationships.
// You can define custom methods on it to extend its functionality as needed.
type termRelationshipsDao struct {
	*internal.TermRelationshipsDao
}

var (
	// TermRelationships is a globally accessible object for table term_relationships operations.
	TermRelationships = termRelationshipsDao{internal.NewTermRelationshipsDao()}
)

// Add your custom methods and functionality below.
