// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hugecms/internal/dao/internal"
)

// userMetaDao is the data access object for the table user_meta.
// You can define custom methods on it to extend its functionality as needed.
type userMetaDao struct {
	*internal.UserMetaDao
}

var (
	// UserMeta is a globally accessible object for table user_meta operations.
	UserMeta = userMetaDao{internal.NewUserMetaDao()}
)

// Add your custom methods and functionality below.
