/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MallRouteImport } from './routes/_mall'
import { Route as TradeRouteImport } from './routes/_trade'
import { Route as UserRouteImport } from './routes/_user'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as SellerRouteRouteImport } from './routes/seller/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as MallIndexRouteImport } from './routes/_mall/index'
import { Route as MallB2bRouteImport } from './routes/_mall/b2b'
import { Route as MallCouponRouteImport } from './routes/_mall/coupon'
import { Route as MallListRouteImport } from './routes/_mall/list'
import { Route as MallPlusRouteImport } from './routes/_mall/plus'
import { Route as MallSeckillRouteImport } from './routes/_mall/seckill'
import { Route as MallShopRouteImport } from './routes/_mall/shop'
import { Route as TradeCartRouteImport } from './routes/_trade/cart'
import { Route as TradeCheckoutRouteImport } from './routes/_trade/checkout'
import { Route as TradePayRouteImport } from './routes/_trade/pay'
import { Route as UserUserRouteImport } from './routes/_user/user'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as SellerGoodsRouteImport } from './routes/seller/goods'
import { Route as SellerOrdersRouteImport } from './routes/seller/orders'
import { Route as MallItemIdRouteImport } from './routes/_mall/item.$id'
import { Route as MallMerchantSettleRouteImport } from './routes/_mall/merchant.settle'
import { Route as UserUserOrderRouteImport } from './routes/_user/user/order'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MallRoute = MallRouteImport.update({
  id: '/_mall',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/_trade',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRouteRoute = SellerRouteRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const MallIndexRoute = MallIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MallRoute,
} as any)
const MallB2bRoute = MallB2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => MallRoute,
} as any)
const MallCouponRoute = MallCouponRouteImport.update({
  id: '/coupon',
  path: '/coupon',
  getParentRoute: () => MallRoute,
} as any)
const MallListRoute = MallListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => MallRoute,
} as any)
const MallPlusRoute = MallPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => MallRoute,
} as any)
const MallSeckillRoute = MallSeckillRouteImport.update({
  id: '/seckill',
  path: '/seckill',
  getParentRoute: () => MallRoute,
} as any)
const MallShopRoute = MallShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => MallRoute,
} as any)
const TradeCartRoute = TradeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => TradeRoute,
} as any)
const TradeCheckoutRoute = TradeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => TradeRoute,
} as any)
const TradePayRoute = TradePayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => TradeRoute,
} as any)
const UserUserRoute = UserUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => UserRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerGoodsRoute = SellerGoodsRouteImport.update({
  id: '/goods',
  path: '/goods',
  getParentRoute: () => SellerRouteRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRouteRoute,
} as any)
const MallItemIdRoute = MallItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => MallRoute,
} as any)
const MallMerchantSettleRoute = MallMerchantSettleRouteImport.update({
  id: '/merchant/settle',
  path: '/merchant/settle',
  getParentRoute: () => MallRoute,
} as any)
const UserUserOrderRoute = UserUserOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => UserUserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/seller': typeof SellerRouteRouteWithChildren
  '/': typeof MallIndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/b2b': typeof MallB2bRoute
  '/coupon': typeof MallCouponRoute
  '/list': typeof MallListRoute
  '/plus': typeof MallPlusRoute
  '/seckill': typeof MallSeckillRoute
  '/shop': typeof MallShopRoute
  '/cart': typeof TradeCartRoute
  '/checkout': typeof TradeCheckoutRoute
  '/pay': typeof TradePayRoute
  '/user': typeof UserUserRouteWithChildren
  '/seller/goods': typeof SellerGoodsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/item/$id': typeof MallItemIdRoute
  '/merchant/settle': typeof MallMerchantSettleRoute
  '/user/order': typeof UserUserOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof MallIndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/b2b': typeof MallB2bRoute
  '/coupon': typeof MallCouponRoute
  '/list': typeof MallListRoute
  '/plus': typeof MallPlusRoute
  '/seckill': typeof MallSeckillRoute
  '/shop': typeof MallShopRoute
  '/cart': typeof TradeCartRoute
  '/checkout': typeof TradeCheckoutRoute
  '/pay': typeof TradePayRoute
  '/user': typeof UserUserRouteWithChildren
  '/seller/goods': typeof SellerGoodsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/seller': typeof SellerIndexRoute
  '/item/$id': typeof MallItemIdRoute
  '/merchant/settle': typeof MallMerchantSettleRoute
  '/user/order': typeof UserUserOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/seller': typeof SellerRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_mall': typeof MallRouteWithChildren
  '/_trade': typeof TradeRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/chat': typeof ChatRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_mall/b2b': typeof MallB2bRoute
  '/_mall/coupon': typeof MallCouponRoute
  '/_mall/list': typeof MallListRoute
  '/_mall/plus': typeof MallPlusRoute
  '/_mall/seckill': typeof MallSeckillRoute
  '/_mall/shop': typeof MallShopRoute
  '/_trade/cart': typeof TradeCartRoute
  '/_trade/checkout': typeof TradeCheckoutRoute
  '/_trade/pay': typeof TradePayRoute
  '/_user/user': typeof UserUserRouteWithChildren
  '/seller/goods': typeof SellerGoodsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/_mall/': typeof MallIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/_mall/item/$id': typeof MallItemIdRoute
  '/_mall/merchant/settle': typeof MallMerchantSettleRoute
  '/_user/user/order': typeof UserUserOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/seller'
    | '/'
    | '/chat'
    | '/login'
    | '/register'
    | '/b2b'
    | '/coupon'
    | '/list'
    | '/plus'
    | '/seckill'
    | '/shop'
    | '/cart'
    | '/checkout'
    | '/pay'
    | '/user'
    | '/seller/goods'
    | '/seller/orders'
    | '/admin/'
    | '/seller/'
    | '/item/$id'
    | '/merchant/settle'
    | '/user/order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/register'
    | '/b2b'
    | '/coupon'
    | '/list'
    | '/plus'
    | '/seckill'
    | '/shop'
    | '/cart'
    | '/checkout'
    | '/pay'
    | '/user'
    | '/seller/goods'
    | '/seller/orders'
    | '/admin'
    | '/seller'
    | '/item/$id'
    | '/merchant/settle'
    | '/user/order'
  id:
    | '__root__'
    | '/seller'
    | '/_auth'
    | '/_mall'
    | '/_trade'
    | '/_user'
    | '/chat'
    | '/_auth/login'
    | '/_auth/register'
    | '/_mall/b2b'
    | '/_mall/coupon'
    | '/_mall/list'
    | '/_mall/plus'
    | '/_mall/seckill'
    | '/_mall/shop'
    | '/_trade/cart'
    | '/_trade/checkout'
    | '/_trade/pay'
    | '/_user/user'
    | '/seller/goods'
    | '/seller/orders'
    | '/_mall/'
    | '/admin/'
    | '/seller/'
    | '/_mall/item/$id'
    | '/_mall/merchant/settle'
    | '/_user/user/order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SellerRouteRoute: typeof SellerRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MallRoute: typeof MallRouteWithChildren
  TradeRoute: typeof TradeRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  ChatRoute: typeof ChatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mall': {
      id: '/_mall'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_trade': {
      id: '/_trade'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_mall/': {
      id: '/_mall/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MallIndexRouteImport
      parentRoute: typeof MallRoute
    }
    '/_mall/b2b': {
      id: '/_mall/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof MallB2bRouteImport
      parentRoute: typeof MallRoute
    }
    '/_mall/coupon': {
      id: '/_mall/coupon'
      path: '/coupon'
      fullPath: '/coupon'
      preLoaderRoute: typeof MallCouponRouteImport
      parentRoute: typeof MallRoute
    }
    '/_mall/list': {
      id: '/_mall/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof MallListRouteImport
      parentRoute: typeof MallRoute
    }
    '/_mall/plus': {
      id: '/_mall/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof MallPlusRouteImport
      parentRoute: typeof MallRoute
    }
    '/_mall/seckill': {
      id: '/_mall/seckill'
      path: '/seckill'
      fullPath: '/seckill'
      preLoaderRoute: typeof MallSeckillRouteImport
      parentRoute: typeof MallRoute
    }
    '/_mall/shop': {
      id: '/_mall/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof MallShopRouteImport
      parentRoute: typeof MallRoute
    }
    '/_trade/cart': {
      id: '/_trade/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof TradeCartRouteImport
      parentRoute: typeof TradeRoute
    }
    '/_trade/checkout': {
      id: '/_trade/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof TradeCheckoutRouteImport
      parentRoute: typeof TradeRoute
    }
    '/_trade/pay': {
      id: '/_trade/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof TradePayRouteImport
      parentRoute: typeof TradeRoute
    }
    '/_user/user': {
      id: '/_user/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserUserRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/goods': {
      id: '/seller/goods'
      path: '/goods'
      fullPath: '/seller/goods'
      preLoaderRoute: typeof SellerGoodsRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRouteRoute
    }
    '/_mall/item/$id': {
      id: '/_mall/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof MallItemIdRouteImport
      parentRoute: typeof MallRoute
    }
    '/_mall/merchant/settle': {
      id: '/_mall/merchant/settle'
      path: '/merchant/settle'
      fullPath: '/merchant/settle'
      preLoaderRoute: typeof MallMerchantSettleRouteImport
      parentRoute: typeof MallRoute
    }
    '/_user/user/order': {
      id: '/_user/user/order'
      path: '/order'
      fullPath: '/user/order'
      preLoaderRoute: typeof UserUserOrderRouteImport
      parentRoute: typeof UserUserRoute
    }
  }
}

interface SellerRouteRouteChildren {
  SellerGoodsRoute: typeof SellerGoodsRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteRouteChildren: SellerRouteRouteChildren = {
  SellerGoodsRoute: SellerGoodsRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteRouteWithChildren = SellerRouteRoute._addFileChildren(
  SellerRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MallRouteChildren {
  MallB2bRoute: typeof MallB2bRoute
  MallCouponRoute: typeof MallCouponRoute
  MallListRoute: typeof MallListRoute
  MallPlusRoute: typeof MallPlusRoute
  MallSeckillRoute: typeof MallSeckillRoute
  MallShopRoute: typeof MallShopRoute
  MallIndexRoute: typeof MallIndexRoute
  MallItemIdRoute: typeof MallItemIdRoute
  MallMerchantSettleRoute: typeof MallMerchantSettleRoute
}

const MallRouteChildren: MallRouteChildren = {
  MallB2bRoute: MallB2bRoute,
  MallCouponRoute: MallCouponRoute,
  MallListRoute: MallListRoute,
  MallPlusRoute: MallPlusRoute,
  MallSeckillRoute: MallSeckillRoute,
  MallShopRoute: MallShopRoute,
  MallIndexRoute: MallIndexRoute,
  MallItemIdRoute: MallItemIdRoute,
  MallMerchantSettleRoute: MallMerchantSettleRoute,
}

const MallRouteWithChildren = MallRoute._addFileChildren(MallRouteChildren)

interface TradeRouteChildren {
  TradeCartRoute: typeof TradeCartRoute
  TradeCheckoutRoute: typeof TradeCheckoutRoute
  TradePayRoute: typeof TradePayRoute
}

const TradeRouteChildren: TradeRouteChildren = {
  TradeCartRoute: TradeCartRoute,
  TradeCheckoutRoute: TradeCheckoutRoute,
  TradePayRoute: TradePayRoute,
}

const TradeRouteWithChildren = TradeRoute._addFileChildren(TradeRouteChildren)

interface UserUserRouteChildren {
  UserUserOrderRoute: typeof UserUserOrderRoute
}

const UserUserRouteChildren: UserUserRouteChildren = {
  UserUserOrderRoute: UserUserOrderRoute,
}

const UserUserRouteWithChildren = UserUserRoute._addFileChildren(
  UserUserRouteChildren,
)

interface UserRouteChildren {
  UserUserRoute: typeof UserUserRouteWithChildren
}

const UserRouteChildren: UserRouteChildren = {
  UserUserRoute: UserUserRouteWithChildren,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SellerRouteRoute: SellerRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MallRoute: MallRouteWithChildren,
  TradeRoute: TradeRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  ChatRoute: ChatRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
