<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('promotion/search', [\App\Domains\Promotion\Controllers\PromotionController::class, 'search']);
// 新增接口
Route::post('promotion/store', [\App\Domains\Promotion\Controllers\PromotionController::class, 'store']);
// 获取详情接口
Route::get('promotion/show', [\App\Domains\Promotion\Controllers\PromotionController::class, 'show'])->name('promotion.show');
// 更新接口
Route::put('promotion/update', [\App\Domains\Promotion\Controllers\PromotionController::class, 'update']);
// 删除接口
Route::post('promotion/destroy', [\App\Domains\Promotion\Controllers\PromotionController::class, 'destroy']);
