<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Api\Common\Controllers\CaptchaController;
use Illuminate\Support\Facades\Route;

// 获取接口
Route::get('/', [CaptchaController::class, 'index'])->name('index');
