<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('product/search', [\App\Domains\Product\Controllers\ProductController::class, 'search']);
// 新增接口
Route::post('product/store', [\App\Domains\Product\Controllers\ProductController::class, 'store']);
// 获取详情接口
Route::get('product/show', [\App\Domains\Product\Controllers\ProductController::class, 'show'])->name('product.show');
// 更新接口
Route::put('product/update', [\App\Domains\Product\Controllers\ProductController::class, 'update']);
// 删除接口
Route::post('product/destroy', [\App\Domains\Product\Controllers\ProductController::class, 'destroy']);
